### ISSUE TITLE
[Docs Rewrite] Meta-Issue: Guided Learning Paths

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3591]
This is a tracking issue for all work related to adding "guided learning paths" to the docs.

## Tasks

- [ ] Define the desired paths and goals for each
- [ ] Add front page links for the paths
- [ ] Add the necessary content for each path

**Comment by meddy672** [comment]
I'll start here
