### ISSUE TITLE
[Docs Rewrite] Meta-Issue: FAQ

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3597]
This is a tracking issue for all work related to updating the FAQ section.

## Tasks

- [ ] Determine info that should be reflected in other pages
- [ ] Review and clean up links for each entry, including highlighting key links
- [ ] Add "Comparison to Other Tools" section
- [ ] Any other updates listed in #2854
- [ ] Come up with nice FAQ shortlinks again

**Comment by wgao19** [comment]
Would love to work on these! Maybe I'll start with reading existing entries and

> Review and clean up links for each entry, including highlighting key links

And what is it about the shortlinks?

**Comment by markerikson** [comment]
The FAQ still needs some review and cleanup. Some specifics:

- Add a new "Is Redux dead?" entry, because this is literally what people keep asking ( latest example: https://www.reddit.com/r/reactjs/comments/p9eu3t/reddit_uses_reactjs_now_weve_gone_full_recursion/ha03q0y/?context=3 )
- Add a "Comparison with Other Tools" page or something that mentions Context, Apollo, Hooks, React Query, Mobx, etc, and links to articles like https://blog.isquaredsoftware.com/2021/01/context-redux-differences/ . I could see this going somewhere other than the FAQ as well.
- Some of the advice in the FAQ is now out of date compared to what we recommend in the Style Guide, like "how should I organize my files?" and "where should my business logic go?". Those should be updated.
- I'm guessing a number of the links are probably dead by now, and some should be replaced by newer links.
