### ISSUE TITLE
[Docs Rewrite] Meta-Issue: Understanding Redux section

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3600]
This is a tracking issue for all work related to creating a new "Understanding Redux" section

## Goal

Pasting from my original writeup in #3313 :

> This section has several objectives:
>
> - Teach the "prerequisites" needed for Redux, including JS array methods, immutability, etc
> - Teach people how to "think in Redux" (multiple reducers listening to one action, treating actions more as events than "setters", etc)
> - Some details on how Redux works internally
> - Info on when you should use Redux, and why Redux patterns exist. (This should mostly be cribbed from Dan's "You Might Not Need Redux", my "Idiomatic Redux: The Tao of Redux" posts, and Justin Falcone's "What's So Great About Redux?").

## Tasks

- [ ] "Background Concepts" section
  - [ ] Outline content
  - [ ] Move material from "Structuring Reducers"
- [ ] "Thinking in Redux" section
  - Outline content
- [ ] "How does Redux Work?" section
  - [ ] Outline content
- [ ] "History and Design" section
  - [ ] Outline content

**Comment by wgao19** [comment]
Would love to work on these also. But I feel these sections are more subjective than others so maybe will work on them later. Putting up a few resource links first

- [Getting Started with Redux](https://egghead.io/courses/getting-started-with-redux)
- [Building React Applications with Idiomatic Redux](https://egghead.io/courses/building-react-applications-with-idiomatic-redux)
- [Idiomatic Redux: The History and Implementation of React-Redux](https://blog.isquaredsoftware.com/2018/11/react-redux-history-implementation/)
- [Dan's twitter thread](https://twitter.com/dan_abramov/status/1039570011986321408?lang=en) on preferring _how to “think in it”_ over _explaining it in terms of API_

**Comment by markerikson** [comment]
Two great resources on how and why to model actions as events:

- https://github.com/dmmulroy/talks/blob/master/event-driven-redux/slides.pdf
- https://youtu.be/K6OlKeQRCzo?t=2626 / https://rangle.slides.com/yazanalaboudi/deck#/

**Comment by markerikson** [comment]
Totally can't forget @modernserf 's great post on [What's So Great about Redux?](https://www.freecodecamp.org/news/whats-so-great-about-redux-ac16f1cc0f8b/).

**Comment by markerikson** [comment]
A very good summary of the "business logic" approach:

https://twitter.com/FwardPhoenix/status/952972062058074112

> "Can it be done with just dispatch arguments?" -> action creator.
> "Can it be done with previous state and action?" -> reducer
> "Can it be done from just state?" -> probably a component.
> 
> So "where does the business logic lives" -> everywhere.

**Comment by markerikson** [comment]
Might be interesting to reference this bit of "Redux history" I wrote up here:

https://www.reddit.com/r/reactjs/comments/mm43cn/would_redux_survive_without_its_maintainers_high/

**Comment by markerikson** [comment]
"Modeling actions as events":

https://www.reddit.com/r/reactjs/comments/oa5pwe/why_is_it_so_difficult_to_modify_a_deeply_nested/h3ip5gj/

> When we say "model actions as events", it implies a few different things:
> 
> - Naming: "somethingHappened", vs "setThing"
> - Mindset: it's not "setters at a distance", it's "broadcast this info, any code that cares can do something with that info"
> - Code layout: having more logic in a reducer, vs always calculating the entire state first -> sticking it in the action ->  doing `return action.payload` or `state.someValue = action.payload`
> - Handling logic: it's fine for many reducers to update themselves independently in response
> 
> None of that goes away with RTK - it's more about a mental model than specific syntax.
> 
> These aren't absolutes, and in some ways it's a hard mindset shift to grasp. And, tbh, _most_ Redux actions will only ever be handled by one slice reducer in practice.  But, I've seen folks writing separate `setFieldX`, `setFieldY` actions for every individual field in some slice, and that's definitely _not_ the right mental approach.
