### ISSUE TITLE
[Docs Rewrite] Meta-Issue: Other Content

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux#3602]
This is a tracking issue to cover all work related to updating the "Other" section, as well as any other bits of content.

## Tasks

- [x] Drop the "Feedback" page (#3623)
- [ ] Add a "Testimonials" page (#3294 )
- [ ] Rethink the "Troubleshooting" page
