### ISSUE TITLE
[Docs Rewrite] Meta-Issue: Data Fetching and Caching

### ISSUE THREAD

**Issue by phryneas** [reduxjs/redux#3613]
The Docs Rewrite should contain a "Data Fetching and Caching" Page that discusses peculiarities of data-fetching itself as well as implementation advice, both with redux as well as some advice on doing the same without redux.

Topics to be covered;
* [ ] cancellation on new request
* [ ] cache invalidation, as a combination of tracking which cache is currently being used by components and timeouts
* [ ] normalization of API results
* [ ] things to be considered in combination with concurrent mode
* [ ] functions of higher order to generate slices with low boilerplate
* [ ] an overview over middlewares that lend themselves to the topic
* [ ] an overview over non-redux libraries that might be used to achieve similar results

**Comment by markerikson** [comment]
We probably ought to have some advice on working with loading states with and without Suspense in here, too.

**Comment by phryneas** [comment]
Definitely. 
I'm gonna experiment with suspense soon, as I'm also a little involved with https://github.com/async-library/future and https://github.com/async-library/react-async.

One question: **if** it would prove to be useful with suspense - how would you feel about suggesting to store a Promise or thenable in a Redux state? I know, it's not serializable per se, but in combination with a `toJSON` property and a `reviver' function for JSON.parse, we maybe could establish a good pattern on how to work with that.

**Comment by markerikson** [comment]
Still a no, because the serialization check middleware in RSK will throw errors.

**Comment by phryneas** [comment]
Okay, let's see how far we get without it :)
